# Generated by Django 5.0.6 on 2025-12-24 18:00

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True, help_text='ID пользователя', unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Баланс кошелька', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_admin', models.BooleanField(default=False, help_text='Технический кошелек администратора')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'wallets',
                'indexes': [models.Index(fields=['user_id'], name='wallets_user_id_9fb6cf_idx')],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Сумма перевода', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Комиссия системы', max_digits=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Статус транзакции', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_wallet', models.ForeignKey(blank=True, help_text='Кошелек отправителя (null для пополнений)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transactions', to='wallets.wallet')),
                ('to_wallet', models.ForeignKey(help_text='Кошелек получателя', on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transactions', to='wallets.wallet')),
            ],
            options={
                'db_table': 'transactions',
                'indexes': [models.Index(fields=['from_wallet', 'created_at'], name='transaction_from_wa_16d426_idx'), models.Index(fields=['to_wallet', 'created_at'], name='transaction_to_wall_2918f3_idx'), models.Index(fields=['status'], name='transaction_status_505a2f_idx')],
            },
        ),
    ]
