# Generated by Django 5.0.6 on 2025-12-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='transaction_from_wa_16d426_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='transaction_to_wall_2918f3_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='transaction_status_505a2f_idx',
        ),
        migrations.RemoveIndex(
            model_name='wallet',
            name='wallets_user_id_9fb6cf_idx',
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='transactions_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(check=models.Q(('fee__gte', 0)), name='transactions_fee_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(check=models.Q(('balance__gte', 0)), name='wallets_balance_non_negative'),
        ),
    ]
